version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5450:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    image: stock-scraper:latest
    volumes:
      - .:/stocks
    ports:
      - "8001:80"
    depends_on:
      - db
    command: ["./prestart.sh", "db", "uvicorn", "src.app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  postgres_data:

