version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5450:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  swagger:
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    env_file:
      - .env
    command: ["sh", "-c", "./wait-for-it.sh db:5432 -- poetry run alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"]

volumes:
  postgres_data:
