name: AWS Setup

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID_TECHNICAL_USER:
        required: true
      AWS_SECRET_ACCESS_KEY_TECHNICAL_USER:
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TECHNICAL_USER }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TECHNICAL_USER }}
          aws-region: us-east-1