name: Build and Scan with Trivy

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  build_and_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Install dependencies
        run: go mod tidy

      - name: Run unit tests
        run: go test -v ./...

      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl gnupg lsb-release
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          echo 'export PATH=$PATH:/root/.local/bin' >> $GITHUB_ENV
          trivy --version  # Verify Trivy installation

      - name: Build snapshot
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} goreleaser release --snapshot --skip-publish

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/Necraatall/stock_scraper_backend:${{ github.sha }} .

      - name: Scan Docker image for vulnerabilities
        run: |
          trivy image --severity HIGH,CRITICAL --ignore-unfixed ghcr.io/Necraatall/stock_scraper_backend:${{ github.sha }}

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
