name: CI Pipeline tests
# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Job for Trivy scan
  trivy-scan:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Scan Docker image with Trivy
      run: task trivy-scan

  # Job for running Ruff, depends on trivy-scan job
  run-ruff:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    needs: trivy-scan

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run Ruff
      run: task run-ruff

  # Job for running pytest with coverage, depends on run-ruff job
  run-pytest-with-coverage:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    needs: run-ruff

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run pytest with coverage
      run: task run-pytest-with-coverage
