name: Docker Build and Push to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY_ALIAS: d8o8x6c7
      REPOSITORY: lection2
      IMAGE_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TECHNICAL_USER }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_TECHNICAL_USER }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build Docker image
        run: |
        docker build -t ${{ steps.ecr-login.outputs.registry }}/${{ env.REGISTRY_ALIAS }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }} .
        
      - name: Tag Docker image
        run: |
        docker tag ${{ steps.ecr-login.outputs.registry }}/${{ env.REGISTRY_ALIAS }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }} \
        ${{ steps.ecr-login.outputs.registry }}/${{ env.REGISTRY_ALIAS }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
        
      - name: Check Environment Variables
        run: |
          echo "Registry: ${{ steps.ecr-login.outputs.registry }}"
          echo "Registry Alias: $REGISTRY_ALIAS"
          echo "Repository: $REPOSITORY"
          echo "Image Tag: $IMAGE_TAG"
