name: Main CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    uses: Necraatall/stock_scraper_backend/.github/workflows/aws_setup.yaml@main

  docker_build_and_push:
    needs: [setup]
    uses: Necraatall/stock_scraper_backend/.github/workflows/docker_build_and_push.yaml@main

  trivy_scan:
    needs: [docker_build_and_push]
    uses: Necraatall/stock_scraper_backend/.github/workflows/trivy.yaml@main

  terraform_job:
    needs: [setup]
    uses: Necraatall/stock_scraper_backend/.github/workflows/terraform.yaml@main
