name: CI/CD Pipeline - Review and Preparation


on:
  pull_request:
    branches:
      - main
      - 'feature/**'
      - 'bug/**'
      - 'chore/**'
  workflow_dispatch:
  workflow_call:

jobs:
  trivy-scan:
    name: Trivy Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'public.ecr.aws/d8o8x6c7/stock_scraper_backend:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  ruff-scan:
    name: Run Ruff
    runs-on: ubuntu-latest
    needs: trivy-scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ruff
        uses: chartboost/ruff-action@v1
        with:
          args: check ./ --fix
