# .github/workflows/review_and_preparation.yaml
name: CI/CD Pipeline - Review and Preparation

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
      - 'feature/**'
      - 'bug/**'
      - 'chore/**'

jobs:
  trivy-scan:
    name: Trivy Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'public.ecr.aws/d8o8x6c7/stock_scraper_backend:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  ruff-scan:
    name: Run Ruff
    runs-on: ubuntu-latest
    needs: trivy-scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ruff
        uses: chartboost/ruff-action@v1
        with:
          args: check ./ --fix

  # TODO: revision of db, models, migrate,
  # scraper on docker-compose, redis - need create,
  
  # NOT important for the DevOps course
  # will manage it after done graduation tasks
  # test-and-coverage:
  #   name: Run Tests and Check Coverage
  #   runs-on: ubuntu-latest
  #   needs: ruff-scan
  #   env:
  #     TESTING: true
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Log in to Amazon ECR Public
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_TECHNICAL_USER }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_TECHNICAL_USER }}
  #       run: |
  #         aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

  #     - name: Pull Docker image
  #       run: |
  #         docker pull public.ecr.aws/d8o8x6c7/stock_scraper_backend:latest

  #     - name: Run tests and check coverage
  #       env:
  #         TEST_DATABASE_URL: 'sqlite:///./app/tests/test_db/test.db'
  #       run: |
  #         docker run --rm \
  #           -e TESTING=true \
  #           -e TEST_DATABASE_URL=$TEST_DATABASE_URL \
  #           public.ecr.aws/d8o8x6c7/stock_scraper_backend:latest bash -c "poetry run coverage run -m pytest && poetry run coverage report && poetry run coverage html && poetry run coverage-badge -o coverage.svg -f"
      
  #     - name: Upload coverage badge
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: coverage-badge
  #         path: coverage.svg

  #     - name: Upload HTML coverage report
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: html-coverage-report
  #         path: htmlcov

  # TODO: make it for all README.md
  # make github token and place him on the github secrets
  # update-readme:
  #   runs-on: ubuntu-latest
  #   needs: ruff-scan
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.10'

  #     - name: Install tree
  #       run: sudo apt-get install -y tree

  #     - name: Set executable permissions for update_readme_tree.sh
  #       run: chmod +x ./update_readme_tree.sh

  #     - name: Update README.md with directory tree
  #       run: ./update_readme_tree.sh

  #     - name: Get current branch name
  #       id: vars
  #       run: echo "actual_branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

  #     - name: Set git user info
  #       run: |
  #         git config --local user.email "${{ secrets.GIT_USER_EMAIL || 'actions@github.com' }}"
  #         git config --local user.name "${{ secrets.GIT_USER_NAME || 'GitHub Actions' }}"

  #     - name: Commit changes
  #       run: |
  #         git add README.md
  #         git commit -m "Update project README.md with latest directory tree"
  #         git push --force origin HEAD:${{ env.actual_branch }}
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Display README.md contents
  #       run: cat README.md