name: Trivy Scan

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID_TECHNICAL_USER:
        required: true
      AWS_SECRET_ACCESS_KEY_TECHNICAL_USER:
        required: true

jobs:
  trivy_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Task
        run: |
          apt-get update -y
          apt-get install -y curl sudo
          curl -sL https://taskfile.dev/install.sh | sh

      - name: Install Trivy using Taskfile
        run: task install-trivy

      - name: Set environment variables
        run: |
          echo "DOCKER_IMAGE_NAME=${{ secrets.DOCKER_IMAGE_NAME }}" >> $GITHUB_ENV

      - name: Scan Docker image with Trivy
        run: task trivy-scan

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/Necraatall/stock_scraper_backend:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/Necraatall/stock_scraper_backend:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
